### ISSUE TITLE
Error installing cellsjs

### ISSUE THREAD

**Issue by rafagarcia** [cellsjs/cells#1]
Hello,

i have tried three times to install the module but i have this output error:

Error: Cannot find module 'q'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/cellsjs/node_modules/bower/lib/commands/index.js:1:71)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "-g" "install" "cellsjs"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! web-component-tester@3.4.2 postinstall: `node scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the web-component-tester@3.4.2 postinstall script 'node scripts/postinstall.js'.
npm ERR! This is most likely a problem with the web-component-tester package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/postinstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls web-component-tester
npm ERR! There is likely additional logging output above.

There are two people here experiencing the same issue.

Thanks a lot in advance.

**Comment by biaggi** [comment]
Hi, rafa, 

Reading the log, is pointing to wct package, are you using sudo to install the package?

Regards

**Comment by rafagarcia** [comment]
I am not using sudo. I include the npm-debug.log.
Regards.

**Comment by biaggi** [comment]
Problem was solved executing 

"bower cache clean"

**Comment by rafagarcia** [comment]
Installation didn´t succeed. I attach the npm debug log again. Same error trying to find the q module.
[npm-debug.log.zip](https://github.com/cellsjs/cells/files/87129/npm-debug.log.zip)

**Comment by biaggi** [comment]
Can you check if there is a jdk environment running in your laptop?

**Comment by rafagarcia** [comment]
javac -version
No Java runtime present, requesting install.

**Comment by rafagarcia** [comment]
Installation was completed succesfully.
Thanks for the help.

**Comment by biaggi** [comment]
Just to clarify the issue, there was a problem with the package.json, thank you for your patience :)
