### ISSUE TITLE
Where's the lint file that's based uppon ?

### ISSUE THREAD

**Issue by aemonge** [cellsjs/cells#2]
I'm using vim, and there's a amezing plug-in that bring lint errors under the current opened file. But for that i need to know if you're using eslint, jslint, etc... to lint the file.

ty

**Comment by biaggi** [comment]
Hi, Andres, we are using jshint and jscs. 

My reccomendation is to use the editorConfig plugin with the following configuration, cos have been proved that removes all linting warnings

# EditorConfig helps developers define and maintain consistent
# coding styles between different editors and IDEs
# editorconfig.org

root = true


[*]

# Change these settings to your own preference
indent_style = space
indent_size = 2

# We recommend you to keep these unchanged
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.md]
trim_trailing_whitespace = false

Regards :)

**Comment by aemonge** [comment]
Got it !!!! 

But i can't find a .jshintrc to match your same configurations

**Comment by jdzrtz** [comment]
Hi!

You can find the .jshintrc and .jscsrc files in the folder cells-ci-lint/lib (cells-ci-lint is a cellsjs dependency, so it should be available in node_modules).

**Comment by aemonge** [comment]
Thanks a lot !!!!

**Comment by aemonge** [comment]
When copying both jscsrc and jshintrc to my home folder, The errors I get from `cells component:lint` are more than `jshint` and `jscs` combined.... shouldn't they be exactly the same ?

**Comment by jdzrtz** [comment]
Yes they should be the same. `cells component:lint` is just passing those two files to `gulp-jshint` and `gulp-jscs`. It also is running the lint process on html files containing js code in the folder. Maybe you are executing `jshint` and `jscs` only on .js files?

**Comment by aemonge** [comment]
Yup, that seams to be working (:

Ty
